baseURL = "hist-digitized.netlify.app"
title = "History, Digitized"
copyright = "Copyright (c) 2020 Chantal Brousseau"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/documentation/"
    weight = 11

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[params]
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    email = "chantalbrousseau@cmail.carletom.ca"
    github = "https://github.com/ChantalMB"

  [params.prismJS]
    enable = false
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
